// Исходные задания. Полные программы и сборник выпускает build.mjs.
export const tasks=[];
let topic='';
export function section(name){topic=name;}
export function q(title,body,answer,why,decl='',imports='fmt'){
 tasks.push({id:tasks.length+1,topic,title,source:`package main\n${imports ? 'import ('+imports.split(',').map(s=>'"'+s+'"').join(';')+')\n':''}${decl}\nfunc main(){${body}}\n`,kind:'run',answer:answer.trimEnd(),why});
}
export function bad(title,body,diagnostic,why,decl='',imports='fmt'){
 q(title,body,diagnostic,why,decl,imports);tasks.at(-1).kind='compile';
}
section('Константы, iota и контекст');
q('Два деления','const a=5/2; const b=5/2.0; fmt.Printf("%T %v | %T %v\\n",a,a,b,b)','int 2 | float64 2.5','Вид нетипизированных операндов определяет, будет ли константное деление целочисленным.');
bad('Слишком точная константа','var x float64=1e1000; fmt.Println(x)','overflows','Константа имеет произвольную точность, но должна представляться в типе назначения.');
q('Большое сокращение','const n=1<<100; fmt.Println(n>>99)','2','Промежуточная константа не ограничена машинным int; ограничение возникает при материализации.');
bad('Большая константа через any','const n=1<<100; var x any=n; fmt.Println(x)','overflows','Упаковка в интерфейс сначала выбирает тип по умолчанию int.');
q('Типизированное деление','const a int=5; fmt.Printf("%T %v\\n",a/2,a/2)','int 2','Типизированный операнд задаёт тип результата даже в константном выражении.');
bad('Константа дробная для int','const x=3.5; var y int=x; fmt.Println(y)','truncated','Нетипизированность позволяет выбирать тип, но не отбрасывать дробную часть при присваивании.');
q('Rune и число','const x=\'A\'+1; fmt.Printf("%T %v\\n",x,x)','int32 66','В смешанном целочисленном константном выражении вид rune определяет тип по умолчанию.');
q('iota и пропущенное выражение','const(a=1<<iota;b;c=10;d);fmt.Println(a,b,c,d)','1 2 10 10','Пропуск повторяет предыдущее выражение, а не автоматически добавляет iota.');
q('iota в двух колонках','const(a,b=iota,iota+10;c,d);fmt.Println(a,b,c,d)','0 10 1 11','iota растёт по спецификациям ConstSpec, а не по количеству имён.');
q('Пропущенный номер','const(_=iota;a;_;b);fmt.Println(a,b)','1 3','Пустой идентификатор не останавливает счётчик iota.');
q('Тип константы при повторении','const(a uint8=iota;b);fmt.Printf("%T %v\\n",b,b)','uint8 1','Повторяются выражение и явно указанный тип предыдущей спецификации.');
bad('Типизированная константа в другой тип','const a int8=7;var b int64=a;fmt.Println(b)','cannot use','Представимость значения не отменяет несовместимость двух определённых числовых типов.');
q('Сдвиг с типом назначения','var s uint=3;var x uint64=1<<s;fmt.Printf("%T %v\\n",x,x)','uint64 8','В неконстантном сдвиге тип левого операнда выводится из контекста присваивания.');
bad('Сдвиг в float64','var s uint=3;var x float64=1<<s;fmt.Println(x)','must be integer','Контекст делает левый операнд float64, после чего неконстантный сдвиг недопустим.');
q('Константная длина массива','const n=len([3]int{});fmt.Printf("%T %v\\n",n,n)','int 3','len массива может быть константой; значение массива вычислять не требуется.');
bad('Длина среза не константа','const n=len([]int{1,2});fmt.Println(n)','not constant','Размер среза не становится константным из-за литеральной записи элементов.');
q('Точный float до упаковки','const a=0.1+0.2;fmt.Println(a==0.3)','true','Константная арифметика выполняется точно до преобразования в машинный float.');
q('Округление типизированных констант','const a float32=16777216;const b float32=a+1;fmt.Println(a==b)','true','Типизированный результат float32 округляется до представимого значения.');
bad('Минус unsigned-константа','const n uint=1;fmt.Println(-n)','overflows','Отрицательная константа не представима в uint; это не арифметика переменной по модулю.');
q('Комплексная константа в вещественный тип','const z=2+0i;var x float64=z;fmt.Printf("%T %v\\n",x,x)','float64 2','Комплексная константа с нулевой мнимой частью представима в вещественном типе.');
section('Числовые преобразования и границы');
q('Сужение и расширение','var n int16=255;fmt.Println(int8(n),int16(int8(n)))','-1 -1','Сужение отбрасывает старшие биты; последующее расширение восстанавливает знак, а не исходное число.');
q('Отрицательное в unsigned','var n int8=-1;fmt.Println(uint16(n),uint16(uint8(n)))','65535 255','Прямое преобразование расширяет знак; промежуточный uint8 меняет дальнейшее расширение.');
q('Разные маршруты к float','var n int64=16777217;fmt.Println(float64(n),float64(float32(n)))','1.6777217e+07 1.6777216e+07','Промежуточный float32 теряет младший значащий бит.');
q('Дробь к целому','var n=-3.9;fmt.Println(int(n),int(n/2))','-3 -1','Конверсия float в int отбрасывает дробную часть в сторону нуля.');
q('Переполнение переменной','var n int8=127;n++;fmt.Println(n)','-128','Знаковая целочисленная арифметика переменных допускает определённое переполнение.');
bad('Переполнение константной суммы','const n int8=127;fmt.Println(n+1)','overflows','Для типизированного константного результата переполнение запрещено.');
q('Дополнение с разной шириной','var n uint8=0;fmt.Println(^n,^uint16(n),uint16(^n))','255 65535 255','Унарное дополнение действует в ширине типа операнда; порядок конверсии важен.');
q('Сдвиг знака вправо','var a int8=-8;fmt.Println(a>>2,uint8(a)>>2)','-2 62','Знаковый сдвиг сохраняет знак; unsigned-сдвиг заполняет старшие биты нулями.');
q('Большой сдвиг переменной','var a uint8=1;var s uint=8;fmt.Println(a<<s)','0','Результат имеет тип левого операнда и не расширяется под число сдвигов.');
q('Минимум делить на минус один','var a int8=-128;var b int8=-1;fmt.Println(a/b,a%b)','-128 0','Особый случай минимального знакового числа даёт само минимальное число и нулевой остаток.');
q('Знак остатка','a,b:=-7,3;fmt.Println(a/b,a%b,7%(-3))','-2 -1 1','Целочисленное деление округляется к нулю; знак ненулевого остатка совпадает с делимым.');
q('Два типа bool не складываются','var a Flag=true;fmt.Printf("%T %v\\n",!a,!a)','main.Flag false','Логическое отрицание сохраняет определённый булев тип.','type Flag bool');
bad('Bool в число','var b=true;fmt.Println(int(b))','cannot convert','Go не задаёт числовой конверсии логических значений.');
bad('Complex-переменная в float','var z complex128=2;fmt.Println(float64(z))','cannot convert','Нулевая мнимая часть переменной не разрешает конверсию complex в float; нужен real.');
q('Тип real','var z complex64=3+4i;fmt.Printf("%T %T\\n",real(z),imag(z))','float32 float32','Компоненты complex64 имеют тип float32.');
bad('complex с разными float','var a float32=1;var b float64=2;fmt.Println(complex(a,b))','mismatched types','Два типизированных аргумента complex должны иметь одинаковый вещественный тип.');
q('NaN и преобразование ширины','x:=math.NaN();fmt.Println(x==x,float32(x)==float32(x))','false false','Изменение ширины float не делает NaN равным самому себе.','','fmt,math');
q('Отрицательный ноль','z:=math.Copysign(0,-1);fmt.Println(z==0,math.Signbit(z),math.Signbit(float64(float32(z))))','true true true','Численное равенство нулей совместимо с сохранением знакового бита при конверсии.','','fmt,math');
q('Сложение до и после преобразования','var a,b uint8=200,100;fmt.Println(uint16(a+b),uint16(a)+uint16(b))','44 300','Переполнение до расширения уже уничтожило старшие биты.');
q('Сравнение разной точности','var n int64=9007199254740993;fmt.Println(int64(float64(n))==n)','false','float64 не представляет все int64 точно; обратная конверсия не восстанавливает утраченное.');
section('Определённые типы и алиасы');
q('Алиас сохраняет методы','var x B=4;fmt.Println(x.Double())','8','Алиас обозначает исходный тип вместе с его методами.','type A int;func(a A)Double()A{return a*2};type B=A');
bad('Новый тип теряет методы','var x B=4;fmt.Println(x.Double())','undefined','Определение B через A не наследует методы A.','type A int;func(a A)Double()A{return a*2};type B A');
q('Печать алиаса','var x B;fmt.Printf("%T\\n",x)','main.A','У алиаса нет собственной идентичности во время выполнения.','type A int;type B=A');
bad('Два имени одного case','var x any=1;switch x.(type){case int:case Alias:}','duplicate case','Алиас не создаёт отдельный вариант в type switch.','type Alias=int','');
q('Новый тип в type switch','var x any=N(1);switch x.(type){case int:fmt.Println("int");case N:fmt.Println("N")}','N','Type switch проверяет динамический тип, а не его underlying type.','type N int');
bad('Два числовых имени','var a A=1;var b B=2;fmt.Println(a+b)','mismatched types','Одинаковое представление не разрешает смешанную арифметику разных определённых типов.','type A int;type B int');
q('Нетипизированный литерал и имя','var a A=1;fmt.Printf("%T %v\\n",a+2,a+2)','main.A 3','Представимая нетипизированная константа принимает тип другого операнда.','type A int');
q('Алиас литерала структуры','var a A;var b struct{X int};a=b;fmt.Printf("%T\\n",a)','struct { X int }','Алиас литерала структуры не превращает её в определённый тип.','type A=struct{X int}');
bad('Метод на алиасе int','fmt.Println(1)','cannot define new methods','Алиас предопределённого int не создаёт локальный базовый тип для методов.','type A=int;func(A)F(){}');
q('Метод через локальный алиас','var x T;fmt.Println(x.F())','7','Алиас локального определённого типа может использоваться в получателе метода.','type T int;type A=T;func(A)F()int{return 7}');
bad('Базовый тип получателя — указатель','var p P;_ = p','invalid receiver type','Базовый определённый тип метода не может иметь underlying type указателя.','type P *int;func(P)F(){}','');
q('Разный тип одинаковых массивов','a:=A{1,2};b:=B(a);fmt.Printf("%T %T %v\\n",a,b,a==A(b))','main.A main.B true','Явная конверсия разрешена при одинаковых underlying types.','type A [2]int;type B [2]int');
bad('Срезы разных имён элементов','a:=[]A{1};fmt.Println([]int(a))','cannot convert','Совпадение underlying type элемента не делает []A и []int одинаковыми underlying types.','type A int');
q('Именованный срез к обычному','a:=A{1};b:=[]int(a);b[0]=9;fmt.Println(a)','[9]','Конверсия среза не копирует массив элементов.','type A []int');
q('Имя функции и литерал','var f F=func(x int)int{return x+1};fmt.Println(f(4))','5','Присваивание допустимо: underlying types совпадают, один из типов не определённый.','type F func(int)int');
bad('Два определённых типа функций','var f F;var g G=f;_ = g','cannot use','Имена параметров не важны, но два разных определённых функциональных типа требуют конверсии.','type F func(int)int;type G func(int)int','');
q('Конверсия функции','f:=F(func(x int)int{return x+1});g:=G(f);fmt.Println(g(4))','5','Конверсия меняет статический тип функции, сохраняя вызываемое значение.','type F func(int)int;type G func(int)int');
q('Рекурсивный тип через срез','var n Node;n=append(n,nil);fmt.Println(len(n),n[0]==nil)','1 true','Срез разрывает рекурсию размера: его заголовок имеет конечный размер.','type Node []Node');
bad('Рекурсивный тип через массив','var n Node;_ = n','invalid recursive type','Массив не разрывает рекурсию определения размера, даже при нулевой длине.','type Node [0]Node','');
bad('Алиас сам на себя','fmt.Println("ok")','invalid recursive type','Алиас обязан обозначать уже определимый тип; цикл алиасов его не создаёт.','type A = *A');
section('Идентичность, присваивание и конверсии');
q('Структура и её литеральный тип','var a A;var b struct{X int};a=b;fmt.Println(a)','{0}','При одинаковом underlying type достаточно, чтобы один тип не был определённым.','type A struct{X int}');
bad('Имена полей имеют значение','a:=struct{X int}{1};var b struct{Y int}=a;fmt.Println(b)','cannot use','Идентичность структур учитывает имена полей, не только их типы и порядок.');
bad('Теги мешают присваиванию','a:=struct{X int `json:"x"`}{1};var b struct{X int `json:"y"`}=a;fmt.Println(b)','cannot use','Теги участвуют в идентичности типов при присваивании.');
q('Теги не мешают конверсии','a:=struct{X int `json:"x"`}{1};b:=struct{X int `json:"y"`}(a);fmt.Println(b)','{1}','При явной конверсии структур соответствующие теги игнорируются.');
q('Конверсия указателей с тегами','a:=struct{X int `json:"x"`}{1};b:=(*struct{X int `json:"y"`})(&a);b.X=9;fmt.Println(a.X)','9','Допустимая конверсия указателей сохраняет адрес и общее хранилище.');
bad('Встроенное поле не обычное','a:=struct{T}{1};var b struct{T T}=a;fmt.Println(b)','cannot use','Embedded-признак поля входит в идентичность структуры.','type T int');
bad('Порядок полей','a:=struct{X int;Y string}{1,"a"};fmt.Println(struct{Y string;X int}(a))','cannot convert','Переупорядочивание полей меняет underlying type, даже если имена совпадают.');
q('Имена аргументов функции','var f func(x int)(y int)=func(z int)int{return z};var g func(int)int=f;fmt.Println(g(8))','8','Имена параметров и результатов не входят в идентичность функционального типа.');
bad('Variadic не обычный срез','var f func(...int);var g func([]int)=f;_ = g','cannot use','Признак variadic входит в тип функции.','','');
bad('Ковариантности результата нет','var f func()any=func()int{return 1};fmt.Println(f())','cannot use','Присваиваемость int в any не распространяется на типы функций, возвращающих эти значения.');
bad('Контравариантности аргумента нет','var f func(int)=func(any){};f(1)','cannot use','Функция с аргументом any не имеет тип func(int), хотя отдельный вызов с int допустим.','','');
q('Указатели на разные имена','var a A=3;b:=(*B)(&a);*b=7;fmt.Println(a)','7','Для неназванных указателей разрешена конверсия при одинаковых underlying types базовых типов.','type A int;type B int');
bad('Присваивание тех же указателей','var a *A;var b *B=a;_ = b','cannot use','Правило конверсии указателей шире правила их присваивания.','type A int;type B int','');
q('Именованная map и обычная','a:=M{"x":1};var b map[string]int=a;b["x"]=2;fmt.Println(a["x"])','2','Присваивание карты сохраняет общую таблицу; один тип не определённый.','type M map[string]int');
bad('Конверсия map по ключу','a:=map[K]int{};fmt.Println(map[string]int(a))','cannot convert','Underlying type карты включает точный тип ключа, а не его underlying type.','type K string');
bad('Конверсия контейнера интерфейсов','a:=[]int{1};fmt.Println([]any(a))','cannot convert','Каждый элемент можно упаковать в any, но преобразования всего среза не существует.');
q('Алиас элемента контейнера','a:=[]A{1};var b []int=a;fmt.Println(b)','[1]','Алиас элемента сохраняет идентичность всего составного типа.','type A=int');
bad('Инициализация определяется справа','x:=1;x=int64(2);fmt.Println(x)','cannot use','Короткое объявление фиксирует тип; последующие присваивания его не меняют.');
q('Тень другого типа','x:=1;{x:="one";fmt.Printf("%T ",x)};fmt.Printf("%T\\n",x)','string int','Новое объявление во вложенном блоке создаёт другую переменную, сохраняя внешнюю.');
bad('Повторное короткое объявление','x:=1;x,y:=int64(2),3;fmt.Println(x,y)','cannot use','Повторно объявленный x в том же блоке сохраняет тип, хотя y — новый.');
section('Интерфейсы, nil и assertions');
q('Типизированный nil в error','var p *E;var e error=p;fmt.Println(p==nil,e==nil)','true false','Интерфейс хранит динамический тип *E даже при nil-указателе.','type E struct{};func(*E)Error()string{return "E"}');
q('Пустой интерфейс из error','var e error;var a any=e;fmt.Println(a==nil)','true','Присваивание nil-интерфейса другому интерфейсу не добавляет динамический тип.');
q('Смена интерфейса сохраняет тип','var e error=(*E)(nil);var a any=e;fmt.Printf("%T %v\\n",a,a==nil)','*main.E false','Внешний any содержит конкретный динамический тип, а не вложенный контейнер error.','type E struct{};func(*E)Error()string{return "E"}');
q('Assertion nil-указателя','var a any=(*int)(nil);p,ok:=a.(*int);fmt.Println(p==nil,ok)','true true','Успех assertion определяется типом; nil является допустимым значением *int.');
q('Assertion nil-интерфейса','var a any;p,ok:=a.(*int);fmt.Println(p==nil,ok)','true false','У nil-интерфейса нет динамического типа, совпадающего с *int.');
q('Assertion не конверсия','var a any=int32(7);n,ok:=a.(int64);fmt.Println(n,ok)','0 false','Assertion требует точного динамического типа, а не допустимой числовой конверсии.');
q('Assertion с алиасом','var a any=int(7);n,ok:=a.(Alias);fmt.Println(n,ok)','7 true','Алиас обозначает тот же динамический тип int.','type Alias=int');
q('Assertion с новым именем','var a any=int(7);n,ok:=a.(N);fmt.Println(n,ok)','0 false','Определённый N отличается от int, хотя underlying type совпадает.','type N int');
q('nil case не ловит typed nil','var a any=(*int)(nil);switch a.(type){case nil:fmt.Println("nil");case *int:fmt.Println("pointer")}','pointer','case nil соответствует только интерфейсу без динамического типа.');
q('Одна ветка уточняет тип','var a any=int32(7);switch v:=a.(type){case int32:fmt.Printf("%T\\n",v)}','int32','При одном конкретном типе в case переменная ветки имеет этот тип.');
q('Несколько типов в ветке','var a any=int32(7);switch v:=a.(type){case int,int32:_,ok:=v.(int32);fmt.Println(ok)}','true','В многотипной ветке v сохраняет статический тип интерфейса, поэтому assertion допустим.');
bad('Assertion у конкретного значения','var x int=7;fmt.Println(x.(int))','not an interface','Assertion применим к интерфейсному выражению, а не к произвольному значению.');
q('Обратная проверка более широкого интерфейса','var r R=T{};_,ok:=r.(W);fmt.Println(ok)','true','Assertion проверяет динамический тип T и может открыть методы, отсутствующие у статического R.','type R interface{Read()};type W interface{Write()};type T struct{};func(T)Read(){};func(T)Write(){}');
bad('Невозможный assertion','var r R;_ = r.(T)','impossible type assertion','Компилятор отвергает конкретный T, который заведомо не реализует исходный интерфейс.','type R interface{Read()};type T struct{}','');
q('Копия значения в интерфейсе','s:=S{1};var a any=s;s.X=2;fmt.Println(a.(S).X,s.X)','1 2','Присваивание структуры интерфейсу копирует значение структуры.','type S struct{X int}');
q('Указатель внутри интерфейса','s:=S{1};var a any=&s;s.X=2;fmt.Println(a.(*S).X)','2','Копируется указатель; объект остаётся общим.','type S struct{X int}');
bad('Поле извлечённой структуры','var a any=S{1};a.(S).X=2','cannot assign','Значение, полученное assertion структуры, не адресуемо.','type S struct{X int}','');
q('Срез внутри копии интерфейса','s:=[]int{1};var a any=s;s[0]=2;fmt.Println(a.([]int))','[2]','Копируется заголовок среза, а не его элементы.');
q('Сравнение nil-среза в интерфейсе с nil','var s []int;var a any=s;fmt.Println(a==nil)','false','Сравнение с nil проверяет отсутствие динамического типа и не сравнивает содержимое среза.');
q('Nil-safe метод','var e error=(*E)(nil);fmt.Println(e.Error())','empty','Вызов метода через интерфейс допустим с nil-получателем, если тело умеет его обработать.','type E struct{};func(e *E)Error()string{if e==nil{return "empty"};return "full"}');
section('Сравнимость и равенство');
q('Разные динамические типы','var a any=int32(1);var b any=int64(1);fmt.Println(a==b)','false','Интерфейсное равенство сначала требует одинаковых динамических типов.');
q('Два интерфейса с одним nil-указателем','var a any=(*int)(nil);var b any=(*int)(nil);fmt.Println(a==b)','true','Указатели сравнимы, динамические типы совпадают, оба значения nil.');
q('Разные несравнимые типы','var a any=[]int{};var b any=map[int]int{};fmt.Println(a==b)','false','Различие динамических типов позволяет вернуть false, не сравнивая значения.');
q('Одинаковые несравнимые типы','defer func(){fmt.Println(recover()!=nil)}();var a any=[]int{};fmt.Println(a==a)','true','При одинаковом динамическом типе среза сравнение интерфейсов вызывает panic.');
bad('Структура с пустым срезом','a:=S{};fmt.Println(a==a)','cannot be compared','Сравнимость определяется типом поля; nil или нулевая длина среза её не меняют.','type S struct{X []int}');
bad('Массив нулевой длины срезов','a:=[0][]int{};fmt.Println(a==a)','cannot be compared','Для сравнимости массива требуется сравнимость типа элемента даже при длине ноль.');
q('Массив интерфейсов','defer func(){fmt.Println(recover()!=nil)}();a:=[1]any{[]int{}};fmt.Println(a==a)','true','Массив статически сравним, но динамическое сравнение его интерфейсного элемента может паниковать.');
q('Ранняя остановка сравнения структуры','a:=S{1,[]int{}};b:=S{2,[]int{}};fmt.Println(a==b)','false','Поля сравниваются в порядке объявления; первое различие исключает опасное сравнение интерфейса.','type S struct{N int;X any}');
q('Перестановка полей меняет исход','defer func(){fmt.Println(recover()!=nil)}();a:=S{[]int{},1};b:=S{[]int{},2};fmt.Println(a==b)','true','Несравнимое динамическое значение встречается до различающегося числового поля.','type S struct{X any;N int}');
bad('Функция сравнивается только с nil','f:=func(){};fmt.Println(f==f)','can only be compared to nil','Функциональные значения не имеют операции равенства друг с другом.');
q('Nil-функция в any','var f func();var a any=f;fmt.Println(f==nil,a==nil)','true false','Функция допускает проверку на nil, но интерфейс с её типом не равен nil.');
q('Указатели на разные переменные','a,b:=7,7;fmt.Println(&a==&b,*(&a)==*(&b))','false true','Равенство указателей сравнивает идентичность ненулевых по размеру переменных, а не их значения.');
q('Конверсия направленного канала','c:=make(chan int);var r <-chan int=c;fmt.Println(c==r)','true','Перед сравнением разрешена совместимая конверсия направления; канал остаётся тем же.');
bad('Несовместимые направления','c:=make(chan int);var r <-chan int=c;var s chan<- int=c;fmt.Println(r==s)','invalid operation','Ни один из двух однонаправленных типов не присваивается другому.');
q('NaN внутри структуры','a:=struct{F float64}{math.NaN()};fmt.Println(a==a)','false','Структурное равенство наследует нерефлексивность сравнения NaN.','','fmt,math');
q('NaN за одним указателем','x:=math.NaN();a,b:=&x,&x;fmt.Println(a==b,*a==*b)','true false','Равенство адресов не сравнивает содержимое float.','','fmt,math');
q('Пустое поле структуры','a:=S{X:1};b:=S{X:1};fmt.Println(a==b)','true','Пустые поля не участвуют в сравнении значений структуры.','type S struct{_ int;X int}');
bad('Пустое несравнимое поле','a:=S{};fmt.Println(a==a)','cannot be compared','Хотя значения пустых полей пропускаются, их типы всё равно определяют сравнимость структуры.','type S struct{_ []int;X int}');
q('DeepEqual и nil-срез','var a []int;b:=[]int{};fmt.Println(reflect.DeepEqual(a,b))','false','DeepEqual различает nil-срез и выделенный пустой срез.','','fmt,reflect');
q('Equal и nil-срез','var a []int;b:=[]int{};fmt.Println(slices.Equal(a,b))','true','slices.Equal сравнивает длину и элементы; nilness не входит в этот договор.','','fmt,slices');
section('Множества методов и получатели');
q('Автоматический адрес','var t T;t.Inc();fmt.Println(t)','1','Адресуемое значение допускает сокращение t.Inc() до (&t).Inc().','type T int;func(t *T)Inc(){*t++}');
bad('Автоматический адрес не для интерфейса','var t T;var i interface{Inc()}=t;_ = i','does not implement','Удобство вызова на адресуемой переменной не добавляет указательные методы в множество методов T.','type T int;func(t *T)Inc(){*t++}','');
bad('Метод у результата функции','makeT().Inc()','cannot call pointer method','Результат функции не адресуем, поэтому автоматическое взятие адреса невозможно.','type T int;func(t *T)Inc(){};func makeT()T{return 0}','');
bad('Метод у элемента map','m:=map[int]T{0:0};m[0].Inc()','cannot call pointer method','Элемент карты не адресуем.','type T int;func(t *T)Inc(){}','');
q('Метод у элемента среза','s:=[]T{0};s[0].Inc();fmt.Println(s[0])','1','Элемент среза адресуем даже при передаче среза по значению.','type T int;func(t *T)Inc(){*t++}');
q('Value receiver сохраняется в method value','t:=T(1);f:=t.Get;t=2;fmt.Println(f(),t.Get())','1 2','Method value с получателем-значением сохраняет копию получателя в момент создания.','type T int;func(t T)Get()T{return t}');
q('Pointer receiver в method value','t:=T(1);f:=t.Get;t=2;fmt.Println(f())','2','При указательном получателе method value сохраняет адрес исходной переменной.','type T int;func(t *T)Get()T{return *t}');
q('Смена переменной указателя','a,b:=T(1),T(2);p:=&a;f:=p.Get;p=&b;fmt.Println(f(),p.Get())','1 2','Method value сохраняет текущее значение указателя, а не переменную p.','type T int;func(t *T)Get()T{return *t}');
q('Метод-выражение добавляет параметр','f:=T.Get;fmt.Printf("%T %v\\n",f,f(7))','func(main.T) main.T 7','Method expression превращает получателя в явный первый аргумент.','type T int;func(t T)Get()T{return t}');
q('Value-метод через указательный тип','f:=(*T).Get;t:=T(7);fmt.Println(f(&t))','7','Множество методов *T включает value-методы T; адаптер разыменовывает аргумент.','type T int;func(t T)Get()T{return t}');
bad('Pointer-метод через T','_ = T.Inc','invalid method expression','Method expression не выполняет автоматическое взятие адреса получателя.','type T int;func(*T)Inc(){}','');
q('Value receiver не меняет число','t:=T(1);t.Inc();fmt.Println(t)','1','Метод изменяет собственную копию скалярного получателя.','type T int;func(t T)Inc(){t++}');
q('Value receiver со срезом','t:=T{[]int{1}};t.Change();fmt.Println(t.S)','[9]','Копия структуры сохраняет общий массив среза, поэтому изменение элемента видно снаружи.','type T struct{S []int};func(t T)Change(){t.S[0]=9}');
q('Value receiver и новый заголовок','t:=T{[]int{1}};t.Clear();fmt.Println(len(t.S))','1','Присваивание поля копии структуры не меняет заголовок среза исходного объекта.','type T struct{S []int};func(t T)Clear(){t.S=nil}');
q('Nil pointer вызывает собственный метод','var t *T;fmt.Println(t.IsNil())','true','Передача nil-получателя сама по себе не паника; важно тело метода.','type T int;func(t *T)IsNil()bool{return t==nil}');
q('Nil pointer вызывает value-метод','defer func(){fmt.Println(recover()!=nil)}();var t *T;fmt.Println(t.Get())','true','Для value-метода требуется разыменовать nil ещё до выполнения тела.','type T int;func(t T)Get()int{return 1}');
q('Изменение через interface','t:=T(1);var i interface{Inc()}=&t;i.Inc();fmt.Println(t)','2','Интерфейс содержит адрес исходного значения, и метод меняет его.','type T int;func(t *T)Inc(){*t++}');
bad('Имена параметров не перегрузка','fmt.Println(T(0))','already declared','Go не поддерживает перегрузку методов даже при разных типах аргументов.','type T int;func(T)F(int){};func(T)F(string){}');
bad('Собственный результат вместо интерфейсного','var x interface{Clone()any}=T{};_ = x','does not implement','Метод Clone()T не реализует Clone()any: ковариантного результата нет.','type T struct{};func(T)Clone()T{return T{}}','');
q('Изменение интерфейсной переменной','var i interface{Get()int}=T(1);f:=i.Get;i=T(2);fmt.Println(f(),i.Get())','1 2','Method value интерфейса сохраняет его текущее содержимое при создании.','type T int;func(t T)Get()int{return int(t)}');
section('Встраивание и продвижение методов');
q('Встроенное значение и адресуемый внешний объект','var o O;o.Inc();fmt.Println(o.T)','1','Продвинутый pointer-метод доступен через адресуемый внешний объект.','type T int;func(t *T)Inc(){*t++};type O struct{T}');
bad('Внешнее значение не реализует pointer-интерфейс','var i interface{Inc()}=O{};_ = i','does not implement','При встраивании T указательные методы продвигаются в *O, но не в O.','type T int;func(*T)Inc(){};type O struct{T}','');
q('Встроенный указатель меняет множество методов','var i interface{Inc()}=O{new(T)};i.Inc();fmt.Println("ok")','ok','При встраивании *T его указательные методы доступны уже в множестве методов O.','type T int;func(*T)Inc(){};type O struct{*T}');
q('Нулевой embedded pointer','var o O;fmt.Println(o.Nil())','true','Продвинутый pointer-метод может получить nil-встроенное поле и обработать его.','type T int;func(t *T)Nil()bool{return t==nil};type O struct{*T}');
q('Нулевой embedded pointer и value receiver','defer func(){fmt.Println(recover()!=nil)}();var o O;fmt.Println(o.Get())','true','Для value-метода встроенный nil-указатель должен разыменоваться.','type T int;func(T)Get()int{return 1};type O struct{*T}');
bad('Два метода на одной глубине','O{}.F()','ambiguous selector','Два одноимённых продвинутых метода на одинаковой глубине делают селектор неоднозначным.','type A struct{};func(A)F(){};type B struct{};func(B)F(){};type O struct{A;B}','');
q('Явный путь убирает неоднозначность','fmt.Println(O{}.A.F(),O{}.B.F())','A B','Каждый embedded-компонент сохраняет собственные методы; неоднозначен лишь сокращённый селектор.','type A struct{};func(A)F()string{return "A"};type B struct{};func(B)F()string{return "B"};type O struct{A;B}');
q('Собственный метод перекрывает продвижение','fmt.Println(O{}.F(),O{}.T.F())','outer inner','Метод внешнего типа скрывает продвинутый, но не заменяет метод вложенного значения.','type T struct{};func(T)F()string{return "inner"};type O struct{T};func(O)F()string{return "outer"}');
q('Внутренний вызов не виртуальное переопределение','fmt.Println(O{}.G())','inner','Метод T.G вызывает T.F на своём получателе; внешний O.F не переопределяет его.','type T struct{};func(T)F()string{return "inner"};func(t T)G()string{return t.F()};type O struct{T};func(O)F()string{return "outer"}');
q('Более близкое поле побеждает','o:=O{A:A{X:1},X:2};fmt.Println(o.X,o.A.X)','2 1','Разрешение селектора выбирает минимальную глубину.','type A struct{X int};type O struct{A;X int}');
bad('Продвинутое поле в литерале','_ = O{X:1}','unknown field','До правил Go 1.27 ключ составного литерала должен называть непосредственное поле.','type A struct{X int};type O struct{A}','');
q('Правильный вложенный литерал','o:=O{A:A{X:1}};fmt.Println(o.X)','1','Инициализация вложенного значения и сокращённый селектор чтения подчиняются разным правилам.','type A struct{X int};type O struct{A}');
bad('Встроенный интерфейс не поле реализации','var o O;var i interface{F()}=o;_ = i','does not implement','Обычное именованное поле интерфейса не продвигает его методы.','type I interface{F()};type O struct{X I}','');
q('Встроенный интерфейс продвигает метод','o:=O{T{}};fmt.Println(o.F())','7','Embedded-интерфейс делегирует вызов своему динамическому значению.','type I interface{F()int};type T struct{};func(T)F()int{return 7};type O struct{I}');
q('Nil embedded interface','defer func(){fmt.Println(recover()!=nil)}();var o O;o.F()','true','Продвинутый метод nil-интерфейсного поля не имеет динамической реализации.','type I interface{F()};type O struct{I}');
q('Повтор одинакового интерфейсного метода','var i C=T{};fmt.Println(i.F())','1','Встроенные интерфейсы могут повторять полностью одинаковые сигнатуры.','type A interface{F()int};type B interface{F()int};type C interface{A;B};type T struct{};func(T)F()int{return 1}');
bad('Конфликт встроенных интерфейсов','var c C;_ = c','duplicate method','Одинаковое имя с разными сигнатурами невозможно объединить в интерфейс.','type A interface{F()int};type B interface{F()string};type C interface{A;B}','');
q('Алиас определяет имя embedded-поля','o:=O{Alias:T(3)};fmt.Println(o.Alias)','3','Имя встроенного поля берётся из записи алиаса, хотя тип сохраняет идентичность T.','type T int;type Alias=T;type O struct{Alias}');
bad('Встраивание указателя на интерфейс','var o O;_ = o','cannot be a pointer to an interface','Embedded-поле не может быть указателем на интерфейс.','type I interface{F()};type O struct{*I}','');
q('Копирование внешнего объекта с embedded pointer','x:=T(1);a:=O{&x};b:=a;b.Inc();fmt.Println(a.T==b.T,x)','true 2','Копия внешней структуры разделяет встроенный указатель и его состояние.','type T int;func(t *T)Inc(){*t++};type O struct{*T}');
section('Срезы, ёмкость и общее хранилище');
q('Append внутри ёмкости','a:=[]int{1,2,3};b:=a[:1];b=append(b,9);fmt.Println(a,b)','[1 9 3] [1 9]','Срез b имеет доступ к ёмкости исходного массива и перезаписывает соседний элемент.');
q('Полное выражение среза','a:=[]int{1,2,3};b:=a[:1:1];b=append(b,9);fmt.Println(a,b)','[1 2 3] [1 9]','Ограничение capacity вынуждает append выделить отдельный массив.');
q('Два append к одному заголовку','a:=make([]int,1,3);b:=append(a,1);c:=append(a,2);fmt.Println(b,c)','[0 2] [0 2]','Оба append записывают в один и тот же индекс общего массива.');
q('Передача среза не передаёт длину обратно','a:=make([]int,1,2);f(a);fmt.Println(len(a),a[:2])','1 [0 7]','Функция меняет копию заголовка, но запись в общий массив видна при расширении.','func f(s []int){s=append(s,7)}');
q('Append с nil без элементов','var a []int;b:=append(a,[]int{}...);fmt.Println(b==nil)','true','Добавление нуля элементов к nil-срезу не требует создания массива.');
q('Пустой срез после make','a:=make([]int,0);b:=a[:0];fmt.Println(a==nil,b==nil)','false false','Нулевая длина не означает nil-заголовок.');
q('Copy с перекрытием вправо','a:=[]int{1,2,3,4};n:=copy(a[1:],a);fmt.Println(n,a)','3 [1 1 2 3]','copy корректно работает с перекрывающимися областями.');
q('Copy с перекрытием влево','a:=[]int{1,2,3,4};copy(a,a[1:]);fmt.Println(a)','[2 3 4 4]','copy не сокращает длину и не очищает хвост исходного среза.');
q('Append перекрывающегося среза','a:=[]int{1,2,3,4};a=append(a[:1],a[2:]...);fmt.Println(a)','[1 3 4]','Спецификация append допускает перекрытие источника и назначения.');
q('Изменение переменной range','a:=[]int{1,2};for _,v:=range a{v*=10};fmt.Println(a)','[1 2]','Переменная range получает копию элемента.');
q('Изменение будущего элемента range','a:=[]int{1,2,3};for i,v:=range a{fmt.Print(v);if i==0{a[1]=9}};fmt.Println()','193','Копируется заголовок среза; будущие элементы читаются из общего массива при обходе.');
q('Append не удлиняет range','a:=[]int{1,2};for _,v:=range a{a=append(a,v)};fmt.Println(a)','[1 2 1 2]','Количество итераций задаётся длиной сохранённого заголовка до начала цикла.');
q('Новый массив посреди range','a:=[]int{1,2};for i,v:=range a{if i==0{a=append(a,3);a[1]=9};fmt.Print(v)};fmt.Println(a)','12[1 9 3]','После realloc range продолжает читать прежний массив.');
q('Указатель на элемент переживает realloc','a:=[]int{1};p:=&a[0];a=append(a,2);a[0]=9;fmt.Println(*p,a[0])','1 9','Указатель остаётся связан с исходным массивом.');
q('Удаление и очистка хвоста','a:=[]int{1,2,3,4};b:=slices.Delete(a,1,3);fmt.Println(b,a)','[1 4] [1 4 0 0]','В Go 1.22+ slices.Delete очищает освободившийся хвост общего массива.','','fmt,slices');
q('Clip не клонирует','a:=[]int{1,2};b:=slices.Clip(a);b[0]=9;fmt.Println(a,cap(b)==len(b))','[9 2] true','Clip ограничивает capacity, сохраняя общее хранилище существующих элементов.','','fmt,slices');
q('Clone поверхностный','x:=1;a:=[]*int{&x};b:=slices.Clone(a);*b[0]=9;b[0]=nil;fmt.Println(*a[0],b[0]==nil)','9 true','Clone создаёт отдельный массив указателей, но не копирует объекты по ним.','','fmt,slices');
q('Clear не меняет длину','a:=[]int{1,2};clear(a);fmt.Println(a,len(a))','[0 0] 2','clear обнуляет доступные элементы, сохраняя заголовок среза.');
q('Срез до capacity','a:=make([]int,1,3);b:=a[:3];fmt.Println(len(b),b)','3 [0 0 0]','Верхняя граница slicing может выходить за len в пределах cap.');
q('Индекс до capacity, но после len','defer func(){fmt.Println(recover()!=nil)}();a:=make([]int,1,3);fmt.Println(a[2])','true','Индексирование ограничено len; capacity не даёт права читать элемент без расширения среза.');
section('Массивы и указатели на массивы');
q('Срез в массив копирует','s:=[]int{1,2};a:=[2]int(s);s[0]=9;fmt.Println(a,s)','[1 2] [9 2]','Конверсия []T в [N]T создаёт значение массива с копиями элементов.');
q('Срез в указатель сохраняет память','s:=[]int{1,2};p:=(*[2]int)(s);p[0]=9;fmt.Println(s)','[9 2]','Конверсия []T в *[N]T даёт представление общего массива.');
q('Длины мало, ёмкости достаточно','defer func(){fmt.Println(recover()!=nil)}();s:=make([]int,1,3);_ = (*[2]int)(s)','true','Условие конверсии проверяет len среза, а не cap.');
q('Nil в нулевой массив','var s []int;a:=[0]int(s);p:=(*[0]int)(s);fmt.Println(len(a),p==nil)','0 true','Нулевая длина допускает конверсию nil-среза; указательный вариант сохраняет nil.');
q('Пустой не-nil в нулевой указатель','s:=make([]int,0);fmt.Println((*[0]int)(s)==nil)','false','Пустой, но не-nil срез конвертируется в ненулевой указатель на массив нулевой длины.');
q('Нулевой массив как ключ','var s []int;m:=map[[0]int]string{[0]int(s):"yes"};fmt.Println(m[[0]int{}])','yes','Все значения одного нулевого массива равны; срез сам по себе ключом быть не может.');
q('Массив указателей копируется поверхностно','x:=1;s:=[]*int{&x};a:=[1]*int(s);*a[0]=9;fmt.Println(*s[0])','9','Копируются элементы-указатели, а не объекты назначения.');
q('Range по значению массива','a:=[3]int{1,2,3};for i,v:=range a{if i==0{a[1]=9};fmt.Print(v)};fmt.Println(a)','123[1 9 3]','Range сохраняет копию массива, когда нужны значения элементов.');
q('Range по указателю на массив','a:=[3]int{1,2,3};for i,v:=range &a{if i==0{a[1]=9};fmt.Print(v)};fmt.Println()','193','Range по указателю читает элементы оригинального массива.');
q('Nil array pointer и только индекс','var p *[3]int;sum:=0;for i:=range p{sum+=i};fmt.Println(sum)','3','При единственной переменной range и константной длине выражение не требуется вычислять.');
q('Nil array pointer со значениями','defer func(){fmt.Println(recover()!=nil)}();var p *[3]int;for _,v:=range p{fmt.Println(v)}','true','Чтобы получить элемент, цикл должен разыменовать nil-указатель.');
q('len nil array pointer','var p *[7]int;fmt.Println(len(p),cap(p))','7 7','len и cap указателя на массив известны из типа; разыменование не требуется.');
q('Функция внутри len','n:=0;f:=func()*[3]int{n++;return nil};fmt.Println(len(f()),n)','3 1','Наличие вызова функции делает выражение len неконстантным, поэтому вызов выполняется.');
q('Срез локального массива','s:=f();s[0]=9;fmt.Println(s)','[9 2]','Возврат среза локального массива допустим: время жизни хранилища не ограничивается стековым кадром.','func f()[]int{a:=[2]int{1,2};return a[:]}');
bad('Slice временного массива','_ = ([2]int{1,2})[:]','unaddressable value','Для slicing массива само значение массива должно быть адресуемым.','','');
q('Slice указателя на литерал','s:=(&[2]int{1,2})[:];fmt.Println(s)','[1 2]','Указатель на составной литерал предоставляет адресуемый массив.');
bad('Конверсия массивов разной длины','a:=[2]int{1,2};fmt.Println([3]int(a))','cannot convert','Конверсия массивов не дополняет и не обрезает элементы; длина входит в тип.');
q('Копия массива в функции','a:=[2]int{1,2};f(a);fmt.Println(a)','[1 2]','Параметр массива получает собственное значение целиком.','func f(a [2]int){a[0]=9}');
q('Изменение массива через срез в функции','a:=[2]int{1,2};f(a[:]);fmt.Println(a)','[9 2]','Заголовок среза указывает на исходный массив.','func f(s []int){s[0]=9}');
q('Конверсия длинного среза','s:=[]int{1,2,3};fmt.Println([2]int(s))','[1 2]','Для конверсии требуется не точное равенство длин, а наличие первых N элементов.');
section('Карты и типы ключей');
q('Чтение nil map','var m map[string]int;v,ok:=m["x"];fmt.Println(v,ok,len(m))','0 false 0','Чтение nil-карты возвращает нулевой элемент и false.');
q('Запись nil map','defer func(){fmt.Println(recover()!=nil)}();var m map[string]int;m["x"]=1','true','Нулевая карта пригодна для чтения, но не для записи.');
q('Delete и clear nil map','var m map[int]int;delete(m,1);clear(m);fmt.Println(m==nil)','true','Удаление и очистка nil-карты допустимы и не создают таблицу.');
q('Копия карты','a:=map[int]int{1:2};b:=a;b[1]=9;fmt.Println(a[1])','9','Присваивание карты копирует ссылку на таблицу.');
q('Переинициализация параметра карты','m:=map[int]int{1:2};f(m);fmt.Println(m[1])','2','Новое значение параметра map не заменяет переменную вызывающего.','func f(m map[int]int){m=map[int]int{1:9}}');
bad('Адрес элемента карты','m:=map[int]int{1:2};_ = &m[1]','cannot take address','Элементы карты не адресуемы, даже если ключ присутствует.','','');
bad('Поле структуры в map','m:=map[int]S{1:{2}};m[1].X=9','cannot assign','Индексирование карты выдаёт значение, а не адресуемую структуру.','type S struct{X int}','');
q('Структура в map через копию','m:=map[int]S{1:{2}};v:=m[1];v.X=9;m[1]=v;fmt.Println(m[1].X)','9','Изменённую копию структуры нужно записать обратно.','type S struct{X int}');
q('Срез в map','m:=map[int][]int{1:{2}};m[1][0]=9;fmt.Println(m[1])','[9]','Элемент массива, доступный через срез из карты, адресуем независимо от адресуемости заголовка.');
q('Указатель в map','m:=map[int]*S{1:{2}};m[1].X=9;fmt.Println(m[1].X)','9','Разыменование указателя из карты даёт изменяемый объект.','type S struct{X int}');
q('any-ключи одинаковых чисел','m:=map[any]string{int(1):"int",int64(1):"int64"};fmt.Println(len(m),m[1],m[int64(1)])','2 int int64','Ключ интерфейсного типа включает динамический тип значения.');
q('Несравнимый ключ при чтении','defer func(){fmt.Println(recover()!=nil)}();m:=map[any]int{};fmt.Println(m[[]int{1}])','true','Динамический ключ должен быть сравним даже при поиске в пустой карте.');
q('Несравнимый ключ при delete','defer func(){fmt.Println(recover()!=nil)}();m:=map[any]int{};delete(m,[]int{})','true','Удаление тоже требует вычисления допустимого хеша ключа.');
q('NaN-ключ нельзя найти','n:=math.NaN();m:=map[float64]int{n:1};v,ok:=m[n];fmt.Println(len(m),v,ok)','1 0 false','NaN не равен самому себе, поэтому повторный поиск тем же float не находит запись.','','fmt,math');
q('NaN записывается дважды','n:=math.NaN();m:=map[float64]int{};m[n]=1;m[n]=2;fmt.Println(len(m))','2','Вторая запись не равна существующему ключу и создаёт новый элемент.','','fmt,math');
q('Удаление NaN и clear','n:=math.NaN();m:=map[float64]int{n:1};delete(m,n);fmt.Print(len(m)," ");clear(m);fmt.Println(len(m))','1 0','delete не находит NaN по равенству; clear очищает таблицу целиком.','','fmt,math');
q('Нулевые float-ключи','m:=map[float64]int{0:1};m[math.Copysign(0,-1)]=2;fmt.Println(len(m),m[0])','1 2','Положительный и отрицательный нули равны и обозначают один ключ.','','fmt,math');
bad('Дублированный константный ключ','m:=map[int]string{1:"a",1:"b"};fmt.Println(m)','duplicate key','Дубликат вычислимых константных ключей выявляется компилятором.');
q('Повтор переменного ключа','x:=1;m:=map[int]string{x:"a",x:"b"};fmt.Println(len(m),m[1])','1 b','Неконстантные ключи вычисляются при исполнении; последняя запись заменяет значение.');
q('Нулевое значение и отсутствие','m:=map[int]int{1:0};a,okA:=m[1];b,okB:=m[2];fmt.Println(a,b,okA,okB)','0 0 true false','Первого результата индексирования недостаточно, чтобы отличить нулевой элемент от отсутствия.');
section('Функции, замыкания и variadic');
q('Variadic разделяет массив','a:=[]int{1,2};f(a...);fmt.Println(a)','[9 2]','Передача среза через ... использует его хранилище.','func f(x ...int){x[0]=9}');
q('Variadic получает отдельные значения','a,b:=1,2;f(a,b);fmt.Println(a,b)','1 2','Для отдельных аргументов создаётся срез значений; переменные вызывающего не становятся его элементами.','func f(x ...int){x[0]=9}');
q('Пустой variadic и пустой срез','fmt.Println(f(),f([]int{}...))','true false','Отсутствие variadic-аргументов даёт nil-срез; явный пустой срез сохраняет nilness.','func f(x ...int)bool{return x==nil}');
bad('Срез int в variadic any','a:=[]int{1,2};f(a...)','cannot use','... не выполняет поэлементную упаковку []int в []any.','func f(...any){}','');
q('Без ... весь срез — один аргумент','a:=[]int{1,2};f(a)','1 []int','В variadic any сам срез является допустимым единичным значением.','func f(x ...any){fmt.Printf("%d %T\\n",len(x),x[0])}');
q('Замыкание хранит переменную','x:=1;f:=func()int{return x};x=2;fmt.Println(f())','2','Замыкание обращается к захваченной переменной, а не фиксирует её прежнее значение.');
q('Копия перед захватом','x:=1;y:=x;f:=func()int{return y};x=2;fmt.Println(f(),x)','1 2','Захваченная копия y независима от дальнейших изменений x.');
q('Новые range-переменные Go 1.22','var fs []func()int;for _,v:=range []int{1,2,3}{fs=append(fs,func()int{return v})};fmt.Println(fs[0](),fs[1](),fs[2]())','1 2 3','В Go 1.22+ объявленные через := переменные range отдельны для каждой итерации.');
q('Range с присваиванием','var fs []func()int;var v int;for _,v=range []int{1,2,3}{fs=append(fs,func()int{return v})};fmt.Println(fs[0](),fs[1](),fs[2]())','3 3 3','Оператор = использует одну заранее объявленную переменную для всех итераций.');
q('defer фиксирует аргумент','x:=1;defer fmt.Println(x);x=2','1','Аргументы отложенного вызова вычисляются при выполнении defer.');
q('defer-замыкание читает позже','x:=1;defer func(){fmt.Println(x)}();x=2','2','Тело отложенного замыкания читает захваченную переменную при выходе.');
q('defer меняет именованный результат','fmt.Println(f())','2','return присваивает именованный результат, после чего defer может его изменить.','func f()(n int){defer func(){n++}();return 1}');
q('defer и неименованный результат','fmt.Println(f())','1','Возвращаемое значение копируется до запуска defer, меняющего локальную переменную.','func f()int{n:=1;defer func(){n++}();return n}');
q('Nil function создаётся без паники','var f func();defer func(){fmt.Println(recover()!=nil)}();f()','true','Nil-функциональное значение разрешено хранить; паника возникает при вызове.');
q('Nil function в defer','defer func(){fmt.Println(recover()!=nil)}();var f func();defer f();fmt.Println("registered")','registered\ntrue','Отложенный вызов nil-функции паникует при исполнении, а не при регистрации defer.');
q('Closure после конверсии функции','n:=0;f:=F(func()int{n++;return n});g:=G(f);fmt.Println(f(),g())','1 2','Конверсия функционального типа сохраняет общее окружение замыкания.','type F func()int;type G func()int');
q('Два результата как все аргументы','fmt.Println(f(pair()))','7','Многозначный вызов может заполнить весь список аргументов другого вызова.','func pair()(int,int){return 3,4};func f(a,b int)int{return a+b}');
bad('Два результата как часть аргументов','fmt.Println(1,pair())','multiple-value','Многозначный вызов нельзя смешивать с другими аргументами таким способом.','func pair()(int,int){return 2,3}');
q('Сравнение типов функций reflection','a:=func(x int){};b:=func(y int){};fmt.Println(reflect.TypeOf(a)==reflect.TypeOf(b))','true','Типы функций совпадают независимо от имён параметров и идентичности самих функций.','','fmt,reflect');
bad('Return nil в int','fmt.Println(f())','cannot use nil','nil не является универсальным нулевым значением для любого результата.','func f()int{return nil}');
section('Каналы, направления и нулевые значения');
q('Направление при присваивании','c:=make(chan int,1);var s chan<- int=c;var r <-chan int=c;s<-7;fmt.Println(<-r)','7','Двунаправленный канал можно ограничить направлением без создания нового канала.');
bad('Обратное направление','var r <-chan int;var c chan int=r;_ = c','cannot use','Утерянное статическое право отправки не возвращается присваиванием.','','');
bad('Конверсия обратно в двунаправленный','var r <-chan int;_ = (chan int)(r)','cannot convert','Явная конверсия тоже не восстанавливает двунаправленный канал.','','');
bad('Receive из send-only','var s chan<- int;_ = <-s','cannot receive','Направление ограничивает допустимые операции при компиляции.','','');
bad('Close receive-only','var r <-chan int;close(r)','cannot close','Закрытие разрешено только каналу, доступному для отправки.','','');
q('Close send-only','c:=make(chan int);var s chan<- int=c;close(s);v,ok:=<-c;fmt.Println(v,ok)','0 false','Право отправки включает возможность close; чтение закрытого пустого канала возвращает ноль.');
q('Тип нуля закрытого канала','c:=make(chan N);close(c);v,ok:=<-c;fmt.Printf("%T %v %v\\n",v,v,ok)','main.N 0 false','Нулевой результат receive имеет точный тип элемента канала.','type N int');
q('Nil-канал в select','var c chan int;select{case <-c:fmt.Println("receive");default:fmt.Println("default")}','default','Операция над nil-каналом не готова; default позволяет избежать блокировки.');
q('Закрытый канал готов сразу','c:=make(chan int);close(c);select{case v:=<-c:fmt.Println(v);default:fmt.Println("default")}','0','Receive закрытого канала готов, поэтому default не выбирается.');
q('Закрытие nil','defer func(){fmt.Println(recover()!=nil)}();var c chan int;close(c)','true','Nil-канал и открытый пустой канал имеют разное поведение при close.');
q('Буфер переживает close','c:=make(chan int,1);c<-7;close(c);a,okA:=<-c;b,okB:=<-c;fmt.Println(a,okA,b,okB)','7 true 0 false','close не удаляет уже отправленные значения; false приходит после опустошения буфера.');
q('Nil-указатель как обычное сообщение','c:=make(chan *int,1);c<-nil;close(c);p,ok:=<-c;fmt.Println(p==nil,ok)','true true','Нулевое значение элемента не означает закрытие; нужен второй результат receive.');
q('Nil-интерфейс как сообщение','c:=make(chan any,1);c<-nil;close(c);a,ok:=<-c;fmt.Println(a==nil,ok)','true true','Даже nil-интерфейс может быть успешно полученным сообщением.');
bad('Каналы не ковариантны','var c chan int;var a chan any=c;_ = a','cannot use','Совместимость элементов не даёт совместимости контейнеров каналов.','','');
q('Assertion направленного канала','c:=make(chan int);var a any=c;_,ok:=a.(<-chan int);fmt.Println(ok)','false','Assertion проверяет точный динамический тип и не выполняет конверсию направления.');
q('Упаковка уже ограниченного канала','c:=make(chan int);var r <-chan int=c;var a any=r;_,ok:=a.(<-chan int);fmt.Println(ok)','true','В интерфейс попадает статический конкретный тип упаковываемого значения с направлением.');
bad('Два определённых канальных типа','var c C;var r R=c;_ = r','cannot use','Особое присваивание направления требует, чтобы хотя бы один тип был неопределённым.','type C chan int;type R <-chan int','');
q('Промежуточный неназванный канал','c:=make(C,1);var r R=(<-chan int)(c);c<-8;fmt.Println(<-r)','8','Промежуточная конверсия направления и присваивание одинакового underlying type выполняются раздельно.','type C chan int;type R <-chan int');
q('Канал срезов передаёт заголовок','c:=make(chan []int,1);s:=[]int{1};c<-s;s[0]=9;fmt.Println(<-c)','[9]','Передача значения среза не делает копию массива; здесь порядок действий задан последовательно.');
q('Канал массивов передаёт копию','c:=make(chan [1]int,1);a:=[1]int{1};c<-a;a[0]=9;fmt.Println(<-c)','[1]','В отличие от среза массив передаётся целым значением.');
section('Параметры типов и инстанциации');
q('Инстанциации разные','fmt.Println(reflect.TypeOf(Box[int]{})==reflect.TypeOf(Box[int64]{}))','false','Аргументы типов участвуют в идентичности инстанцированного типа.','type Box[T any]struct{V T}','fmt,reflect');
q('Алиас аргумента не различает инстанциации','fmt.Println(reflect.TypeOf(Box[int]{})==reflect.TypeOf(Box[A]{}))','true','Идентичные аргументы типов дают идентичную инстанциацию.','type A=int;type Box[T any]struct{V T}','fmt,reflect');
bad('Нет ковариантности Box','var a Box[int];var b Box[any]=a;_ = b','cannot use','Box[int] и Box[any] не связаны присваиванием, хотя int присваивается any.','type Box[T any]struct{V T}','');
bad('Generic-тип без аргументов','var b Box;_ = b','without instantiation','Тип с параметрами необходимо инстанцировать при использовании.','type Box[T any]struct{V T}','');
q('Нулевое T через var','fmt.Printf("%T %v %q\\n",zero[int](),zero[int](),zero[string]())','int 0 ""','var создаёт нулевое значение конкретного типа после инстанциации.','func zero[T any]()T{var z T;return z}');
bad('Универсальный return nil','fmt.Println(zero[int]())','cannot use nil','Ограничение any включает типы, для которых nil не является значением.','func zero[T any]()T{return nil}');
q('new от параметра типа','p:=makePtr[int]();fmt.Printf("%T %v\\n",p,*p)','*int 0','new(T) создаёт указатель на нулевое значение конкретного T.','func makePtr[T any]()*T{return new(T)}');
bad('Произвольная конверсия между параметрами','fmt.Println(convert[int,string](1))','cannot convert','Тело должно быть корректно для всего множества разрешённых E и R.','func convert[E,R any](x E)R{return R(x)}');
q('Явный callback связывает типы','fmt.Println(mapOne(7,func(n int)string{return fmt.Sprint(n)}))','7','Связь преобразования задаётся функцией, а не неразрешённой универсальной конверсией.','func mapOne[E,R any](x E,f func(E)R)R{return f(x)}');
bad('Assertion непосредственно на T','fmt.Println(isInt(1))','cannot use type assertion','Параметр типа с ограничением any не является интерфейсным выражением для assertion.','func isInt[T any](v T)bool{_,ok:=v.(int);return ok}');
q('Assertion после упаковки T','fmt.Println(isInt(1),isInt(N(1)))','true false','any(v) открывает динамическую проверку точного типа, сохраняя различие определённых типов.','type N int;func isInt[T any](v T)bool{_,ok:=any(v).(int);return ok}');
bad('Type switch непосредственно по T','fmt.Println(kind(1))','cannot use type switch','Type switch требует интерфейсного значения; ограничение any не заменяет упаковку.','func kind[T any](v T)int{switch v.(type){case int:return 1};return 0}');
q('Generic-метод использует параметры типа','b:=Box[string]{"go"};fmt.Println(b.Get())','go','Метод может использовать параметры типа получателя без собственных параметров.','type Box[T any]struct{V T};func(b Box[T])Get()T{return b.V}');
bad('Собственный параметр метода в Go 1.23','fmt.Println(Box[int]{})','method must have no type parameters','В выбранной версии Go 1.23 метод не может объявить новый параметр R.','type Box[T any]struct{V T};func(b Box[T])Map[R any](f func(T)R)R{return f(b.V)}');
q('Имя параметра получателя можно сменить','fmt.Println(Box[int]{3}.Get())','3','В получателе метода параметр типа объявляется заново по позиции.','type Box[T any]struct{V T};func(b Box[E])Get()E{return b.V}');
bad('Получатель не специализация','fmt.Println(Box[int]{3}.Add())','cannot convert','Имя int в Box[int] получателя объявляет параметр типа и скрывает встроенный int, а не специализирует метод.','type Box[T any]struct{V T};func(b Box[int])Add()int{return b.V+1}');
q('Статический T=any сохраняет dynamic int','var a any=7;b:=Box[any]{a};fmt.Printf("%T %T\\n",b,b.V)','main.Box[interface {}] int','Параметр контейнера — any, но значение интерфейсного поля имеет динамический тип int.','type Box[T any]struct{V T}');
bad('Метод T не является методом *T','fmt.Println(f(N(1)))','undefined','*T — указатель на параметр типа, а не параметр с автоматически унаследованным набором методов.','type N int;func(N)F()int{return 1};func f[T interface{F()int}](v T)int{return (&v).F()}');
q('Инстанцированная функция как значение','f:=id[int];fmt.Printf("%T %v\\n",f,f(9))','func(int) int 9','После инстанциации функция имеет обычный конкретный функциональный тип.','func id[T any](v T)T{return v}');
bad('Неиспользуемый параметр не выводится','fmt.Println(f(1))','cannot infer','Параметр R не связан с аргументами и не получает значение автоматически.','func f[T,R any](v T)T{return v}');
section('Множества типов и ограничения');
bad('Точный int не принимает новый тип','fmt.Println(f(N(1)))','does not satisfy','Элемент int в type set включает только int, без определённых типов с таким underlying type.','type N int;func f[T int](v T)T{return v}');
q('Тильда принимает новый тип','fmt.Printf("%T %v\\n",f(N(1)),f(N(1)))','main.N 2','~int допускает определённые типы и сохраняет их в результате T.','type N int;func f[T ~int](v T)T{return v+1}');
bad('Тильда перед определённым типом','fmt.Println(1)','invalid use of ~','У типа после ~ underlying type должен совпадать с самим этим типом.','type N int;type C interface{~N}');
bad('Перекрытие термов объединения','fmt.Println(1)','overlapping terms','Непересекающиеся термы union не могут одновременно включать int и ~int.','type C interface{int|~int}');
q('Оператор общий для union','fmt.Println(twice(3),twice("go"))','6 gogo','Оператор + разрешён и для int, и для string, сохраняя тип T.','func twice[T ~int|~string](v T)T{return v+v}');
bad('Оператор не общий для union','fmt.Println(f(3))','operator - not defined','Разрешённость операции проверяется для всех типов множества, включая string.','func f[T ~int|~string](v T)T{return v-v}');
bad('Поле одинаковое во всех типах','fmt.Println(f(A{1}))','undefined','Объединение структур не предоставляет доступ к полям параметра типа в Go 1.23.','type A struct{X int};type B struct{X int;Y int};func f[T A|B](v T)int{return v.X}');
q('Общий метод в ограничении','fmt.Println(f(N(3)))','6','Перечисленный метод становится доступной операцией параметра типа.','type N int;func(n N)Double()int{return int(n*2)};func f[T interface{Double()int}](v T)int{return v.Double()}');
bad('Union типов не объявляет методы','fmt.Println(f(N(1)))','undefined','Методы конкретных термов не становятся методами ограничения автоматически.','type N int;func(N)F()int{return 1};func f[T N](v T)int{return v.F()}');
bad('Пустое пересечение','fmt.Println(f(1))','empty type set','Несовместимые встроенные ограничения пересекаются, образуя пустое множество.','type C interface{int;string};func f[T C](v T)T{return v}');
bad('Constraint нельзя хранить как значение','var x C;_ = x','outside a type constraint','Интерфейс с type terms предназначен для ограничений, а не для runtime-значений.','type C interface{~int|~string}','');
bad('comparable как обычный интерфейс','var c comparable;_ = c','outside a type constraint','Предопределённый comparable является ограничением, не обычным контейнером значений.','','');
q('any удовлетворяет comparable','fmt.Println(eq[any](1,1))','true','С Go 1.20 any допускается как аргумент comparable, сохраняя динамические риски сравнения.','func eq[T comparable](a,b T)bool{return a==b}');
q('comparable не защищает от panic','defer func(){fmt.Println(recover()!=nil)}();fmt.Println(eq[any]([]int{},[]int{}))','true','Инстанциация допустима, но динамические значения одного несравнимого типа паниковывают.','func eq[T comparable](a,b T)bool{return a==b}');
bad('Срез не satisfies comparable','fmt.Println(eq([]int{},[]int{}))','does not satisfy comparable','Конкретный тип среза несравним и отвергается статически.','func eq[T comparable](a,b T)bool{return a==b}');
q('len для разных контейнеров','fmt.Println(size("я"),size([]int{1,2,3}))','2 3','len разрешён для всех термов, но его предметный смысл различается: байты строки и элементы среза.','func size[T ~string|~[]int](v T)int{return len(v)}');
q('Индексирование string и []byte','fmt.Printf("%T %v\\n",first("go"),first([]byte{9}))','uint8 9','Индексирование объединения допустимо, когда тип результата совпадает для всех термов.','func first[T ~string|~[]byte](v T)byte{return v[0]}');
bad('Разные типы результата индекса','fmt.Println(first([]int{1}))','cannot index','У []int и []string типы результатов индексирования различны.','func first[T ~[]int|~[]string](v T)any{return v[0]}');
q('Nil при ограничении срезом','fmt.Println(empty[[]int]()==nil)','true','При ~[]E все допустимые типы поддерживают nil.','func empty[S ~[]E,E any]()S{return nil}');
bad('Нельзя усилить ограничение в методе','_ = Set[int]{}','does not satisfy','Метод Set[K] обязан работать для всего comparable, а функция требует более сильный ~int.','type Set[K comparable]struct{};func ordered[T ~int](T){};func(s Set[K])F(k K){ordered(k)}','');
section('Вывод аргументов типов');
q('Тип от первого типизированного аргумента','var n int32=2;fmt.Printf("%T\\n",max(n,3))','int32','Представимая константа принимает тип, выведенный из типизированного аргумента.','func max[T ~int|~int32](a,b T)T{if a>b{return a};return b}');
bad('Два разных типизированных аргумента','var a int32=1;var b int64=2;fmt.Println(same(a,b))','does not match','Вывод не подбирает общий расширенный числовой тип для разных типизированных аргументов.','func same[T any](a,b T)T{return a}');
q('Смешанные нетипизированные константы','fmt.Printf("%T %v\\n",first(1,2.5),first(1,2.5))','float64 1','В Go 1.21+ виды нетипизированных констант рассматриваются совместно.','func first[T any](a,b T)T{return a}');
bad('Непредставимая константа после вывода','var a uint8=1;fmt.Println(first(a,256))','overflows','Вывод выбирает uint8, после чего проверяется представимость второго аргумента.','func first[T any](a,b T)T{return a}');
q('Явный any допускает разные значения','fmt.Printf("%T\\n",first[any](int32(1),"x"))','int32','Явная инстанциация any позволяет отдельно присвоить каждый аргумент интерфейсному параметру.','func first[T any](a,b T)T{return a}');
bad('Нетипизированный nil не задаёт T','fmt.Println(id(nil))','cannot infer','У nil нет типа по умолчанию, который мог бы стать аргументом T.','func id[T any](v T)T{return v}');
q('Типизированный nil задаёт T','fmt.Printf("%T\\n",id((*int)(nil)))','*int','Конкретный тип nil-указателя служит источником вывода.','func id[T any](v T)T{return v}');
bad('Тип назначения вызова не помогает','var x int=zero();fmt.Println(x)','cannot infer','Тип переменной слева не используется для вывода аргумента типа результата вызова.','func zero[T any]()T{var z T;return z}');
q('Тип назначения функции помогает','var f func(int)int=id;fmt.Println(f(9))','9','С Go 1.21 функциональное присваивание инстанцирует generic-функцию по ожидаемой сигнатуре.','func id[T any](v T)T{return v}');
bad('Короткое объявление generic-функции','f:=id;fmt.Println(f(1))','without instantiation','Без целевого функционального типа неинстанцированное имя нельзя сохранить через :=.','func id[T any](v T)T{return v}');
q('Частичный список слева','fmt.Printf("%T %v\\n",convert[int64](int32(7)),convert[int64](int32(7)))','int64 7','Первый параметр задан явно, оставшийся выводится из аргумента.','func convert[To,From ~int32|~int64](v From)To{return To(v)}');
bad('Нельзя пропустить первый аргумент типа','fmt.Println(pair[_,int](1,2))','cannot use _','Список явных аргументов должен быть префиксом; _ не служит пропуском.','func pair[A,B any](a A,b B)A{return a}');
q('Связь с элементом через constraint','x:=clone(N{1,2});fmt.Printf("%T %v\\n",x,x)','main.N [1 2]','Сначала выводится S=N, затем из ~[]E извлекается E=int; результат сохраняет имя среза.','type N []int;func clone[S ~[]E,E any](s S)S{return append(S(nil),s...)}');
q('Потеря имени среза в другой сигнатуре','x:=clone(N{1,2});fmt.Printf("%T\\n",x)','[]int','Сигнатура []E возвращает неназванный срез, хотя вход допускает именованный N.','type N []int;func clone[E any](s []E)[]E{return append([]E(nil),s...)}');
q('Вывод из метода интерфейса','fmt.Printf("%T %v\\n",read(S{}),read(S{}))','int 7','В Go 1.21+ сопоставление метода Read выводит связанный тип результата T.','type S struct{};func(S)Read()int{return 7};func read[T any](s interface{Read()T})T{return s.Read()}');
q('Generic-функция как callback','fmt.Println(apply(3,id))','3','Тип аргумента и требуемый тип callback совместно позволяют инстанцировать id.','func id[T any](v T)T{return v};func apply[T any](v T,f func(T)T)T{return f(v)}');
q('Nil подстраивается под другой аргумент','var p *int;fmt.Println(first(p,nil)==nil)','true','nil не выводит тип сам, но подходит под *int, уже выведенный из другого аргумента.','func first[T any](a,b T)T{return a}');
q('Вывод по именованному каналу','c:=make(C,1);c<-7;fmt.Println(read(c))','7','Параметр receive-only допускает двунаправленный аргумент, а тип элемента выводится.','type C chan int;func read[T any](c <-chan T)T{return <-c}');
q('Variadic выводит один тип','fmt.Printf("%T %v\\n",first(1,2.5),first(1,2.5))','float64 1','Все variadic-аргументы участвуют в выводе одного T.','func first[T any](v ...T)T{return v[0]}');
bad('Пустой variadic не выводит T','fmt.Println(count())','cannot infer','Нет элементов и нет других связей, из которых можно определить T.','func count[T any](v ...T)int{return len(v)}');
section('Reflection: типы и отношения');
q('TypeOf nil','fmt.Println(reflect.TypeOf(nil)==nil)','true','Без динамического типа TypeOf возвращает nil, а не описание интерфейса.','','fmt,reflect');
q('TypeOf typed nil','var p *int;t:=reflect.TypeOf(p);fmt.Println(t==nil,t.Kind(),t.Elem())','false ptr int','Тип nil-указателя существует независимо от отсутствия объекта.','','fmt,reflect');
q('Kind не идентичность','a,b:=reflect.TypeOf(N(1)),reflect.TypeOf(1);fmt.Println(a.Kind()==b.Kind(),a==b,a.Name())','true false N','Kind описывает категорию представления и не стирает различие определённых типов.','type N int','fmt,reflect');
q('TypeFor интерфейса','var a any=1;fmt.Println(reflect.TypeOf(a).Kind(),reflect.TypeFor[any]().Kind())','int interface','TypeOf исследует динамический тип значения; TypeFor получает явно заданный тип.','','fmt,reflect');
q('AssignableTo и ConvertibleTo','a,b:=reflect.TypeOf(int32(1)),reflect.TypeOf(int64(1));fmt.Println(a.AssignableTo(b),a.ConvertibleTo(b))','false true','Числовое преобразование может быть допустимо без допустимого присваивания.','','fmt,reflect');
q('Срезы с разными элементами','a,b:=reflect.TypeOf([]N{}),reflect.TypeOf([]int{});fmt.Println(a.ConvertibleTo(b))','false','Reflection следует обычным правилам конверсии и не добавляет поэлементный обход.','type N int','fmt,reflect');
q('Теги в reflection','a:=reflect.TypeOf(struct{X int `a:"1"` }{});b:=reflect.TypeOf(struct{X int `a:"2"` }{});fmt.Println(a==b,a.AssignableTo(b),a.ConvertibleTo(b))','false false true','Теги различают типы и присваивание, но игнорируются при структурной конверсии.','','fmt,reflect');
q('Implements учитывает receiver','i:=reflect.TypeFor[interface{F()}]();fmt.Println(reflect.TypeFor[T]().Implements(i),reflect.TypeFor[*T]().Implements(i))','false true','Reflection использует реальные множества методов T и *T без автоматического взятия адреса.','type T int;func(*T)F(){}','fmt,reflect');
q('Число методов конкретного типа','fmt.Println(reflect.TypeFor[T]().NumMethod())','1','Для конкретного неинтерфейсного типа reflection перечисляет только экспортируемые методы.','type T int;func(T)F(){};func(T)hidden(){}','fmt,reflect');
q('Число методов интерфейса','fmt.Println(reflect.TypeFor[I]().NumMethod())','2','Для интерфейса NumMethod включает и неэкспортируемые методы.','type I interface{F();hidden()}','fmt,reflect');
q('Comparable Type и Comparable Value','v:=reflect.ValueOf(struct{X any}{[]int{}});fmt.Println(v.Type().Comparable(),v.Comparable())','true false','Тип структуры сравним статически, но Value учитывает конкретное динамическое содержимое.','','fmt,reflect');
q('CanConvert проверяет длину','v:=reflect.ValueOf([]int{1});t:=reflect.TypeFor[*[2]int]();fmt.Println(v.Type().ConvertibleTo(t),v.CanConvert(t))','true false','Отношение типов допускает конверсию, но конкретный срез слишком короток.','','fmt,reflect');
q('Convert не защищён ConvertibleTo','defer func(){fmt.Println(recover()!=nil)}();v:=reflect.ValueOf([]int{1});_ = v.Convert(reflect.TypeFor[[2]int]())','true','Convert может паниковать из-за значения длины, несмотря на допустимое отношение типов.','','fmt,reflect');
q('Имя среза и имя элемента','t:=reflect.TypeFor[[]N]();fmt.Printf("%q %s\\n",t.Name(),t.Elem().Name())','"" N','Неназванный составной тип не получает имя от своего определённого элемента.','type N int','fmt,reflect');
q('Метод как reflect.Type','m,_:=reflect.TypeFor[T]().MethodByName("F");fmt.Println(m.Type.NumIn(),m.Type.In(0))','1 main.T','В типе метода конкретного типа получатель является первым аргументом.','type T int;func(T)F(){}','fmt,reflect');
q('Метод интерфейса без receiver-параметра','m,_:=reflect.TypeFor[I]().MethodByName("F");fmt.Println(m.Type.NumIn())','0','Reflection-описание метода интерфейса не включает явный аргумент получателя.','type I interface{F()}','fmt,reflect');
q('ChanDir — часть типа','a:=reflect.TypeFor[chan int]();b:=reflect.TypeFor[<-chan int]();fmt.Println(a==b,a.ChanDir(),b.ChanDir())','false chan <-chan','Одинаковый элемент канала не отменяет различие направлений.','','fmt,reflect');
q('Размер массива — часть типа','a,b:=reflect.ArrayOf(2,reflect.TypeFor[int]()),reflect.TypeFor[[2]int]();fmt.Println(a==b,a.Len())','true 2','Построение описания типа во время выполнения сохраняет обычную идентичность массивов.','','fmt,reflect');
q('StructOf совпадает с неназванной структурой','t:=reflect.StructOf([]reflect.StructField{{Name:"X",Type:reflect.TypeFor[int]()}});fmt.Println(t==reflect.TypeFor[struct{X int}]())','true','Совпадающая структура полей задаёт тот же неназванный структурный тип.','','fmt,reflect');
q('MapOf требует сравнимый ключ','defer func(){fmt.Println(recover()!=nil)}();_ = reflect.MapOf(reflect.TypeFor[[]int](),reflect.TypeFor[int]())','true','Динамическое конструирование типа карты не обходит требование сравнимости ключа.','','fmt,reflect');
section('Reflection: значения и изменяемость');
q('ValueOf копии и адреса','n:=1;fmt.Println(reflect.ValueOf(n).CanSet(),reflect.ValueOf(&n).Elem().CanSet())','false true','Для Set нужен доступ к исходной адресуемой переменной, а не копия её значения.','','fmt,reflect');
q('SetInt сужает','var n int8;reflect.ValueOf(&n).Elem().SetInt(257);fmt.Println(n)','1','SetInt принимает int64 и записывает с усечением до ширины целевого целочисленного типа.','','fmt,reflect');
q('OverflowInt проверяет отдельно','var n int8;v:=reflect.ValueOf(&n).Elem();fmt.Println(v.OverflowInt(257),v.OverflowInt(127))','true false','Проверка представимости отдельна от операции SetInt.','','fmt,reflect');
q('Set требует assignability','defer func(){fmt.Println(recover()!=nil)}();var n int64;reflect.ValueOf(&n).Elem().Set(reflect.ValueOf(int32(1)))','true','Set не выполняет автоматическую числовую конверсию.','','fmt,reflect');
q('Convert перед Set','var n int64;v:=reflect.ValueOf(&n).Elem();v.Set(reflect.ValueOf(int32(7)).Convert(v.Type()));fmt.Println(n)','7','Явное отражённое преобразование создаёт значение требуемого типа до присваивания.','','fmt,reflect');
q('Invalid Value','v:=reflect.ValueOf(nil);fmt.Println(v.IsValid(),v.Kind())','false invalid','Отсутствующее динамическое значение описывается invalid Value.','','fmt,reflect');
q('IsNil у invalid Value','defer func(){fmt.Println(recover()!=nil)}();reflect.ValueOf(nil).IsNil()','true','IsNil требует подходящий Kind; invalid не является nil-интерфейсным Value.','','fmt,reflect');
q('Zero и Invalid различны','v:=reflect.Zero(reflect.TypeFor[any]());fmt.Println(v.IsValid(),v.IsNil(),v.Kind())','true true interface','Zero создаёт валидное описание нулевого значения заданного типа.','','fmt,reflect');
q('Elem nil pointer','var p *int;v:=reflect.ValueOf(p).Elem();fmt.Println(v.IsValid())','false','Разыменование nil через Value.Elem возвращает invalid Value.','','fmt,reflect');
q('Непубличное поле адресуемо','s:=S{x:7};v:=reflect.ValueOf(&s).Elem().Field(0);fmt.Println(v.CanAddr(),v.CanSet(),v.CanInterface(),v.Int())','true false false 7','Reflection позволяет типизированное чтение закрытого поля, но запрещает Set и Interface.','type S struct{x int}','fmt,reflect');
q('Interface закрытого поля','defer func(){fmt.Println(recover()!=nil)}();v:=reflect.ValueOf(S{x:7}).Field(0);_ = v.Interface()','true','Наличие читаемого значения не означает разрешение упаковать неэкспортируемое поле в интерфейс.','type S struct{x int}','fmt,reflect');
q('MapIndex выдаёт копию','m:=map[int]int{1:2};v:=reflect.ValueOf(m).MapIndex(reflect.ValueOf(1));fmt.Println(v.CanAddr(),v.CanSet())','false false','Элемент карты остаётся неадресуемым и через reflection.','','fmt,reflect');
q('SetMapIndex без адресуемой карты','m:=map[int]int{1:2};reflect.ValueOf(m).SetMapIndex(reflect.ValueOf(1),reflect.ValueOf(9));fmt.Println(m[1])','9','Изменение таблицы не требует изменять переменную, хранящую значение map.','','fmt,reflect');
q('Invalid Value удаляет ключ','m:=map[int]int{1:2};reflect.ValueOf(m).SetMapIndex(reflect.ValueOf(1),reflect.Value{});fmt.Println(len(m))','0','Нулевой reflect.Value в SetMapIndex означает удаление, а не запись нуля элемента.','','fmt,reflect');
q('Zero записывает ключ','m:=map[int]int{};reflect.ValueOf(m).SetMapIndex(reflect.ValueOf(1),reflect.Zero(reflect.TypeFor[int]()));v,ok:=m[1];fmt.Println(v,ok)','0 true','Валидное нулевое значение int создаёт элемент карты.','','fmt,reflect');
q('Элемент среза изменяем через ValueOf','s:=[]int{1};v:=reflect.ValueOf(s);fmt.Println(v.CanSet(),v.Index(0).CanSet());v.Index(0).SetInt(9);fmt.Println(s)','false true\n[9]','Неизменяемость копии заголовка не делает элементы общего массива неизменяемыми.','','fmt,reflect');
q('Элемент массива-копии','v:=reflect.ValueOf([1]int{1});fmt.Println(v.Index(0).CanSet())','false','Массив целиком скопирован в ValueOf; доступа к исходной переменной нет.','','fmt,reflect');
q('SetLen требует адрес заголовка','defer func(){fmt.Println(recover()!=nil)}();s:=make([]int,1,3);reflect.ValueOf(s).SetLen(2)','true','Расширение длины меняет сам заголовок среза, который здесь не изменяем.','','fmt,reflect');
q('SetLen через адрес','s:=make([]int,1,3);reflect.ValueOf(&s).Elem().SetLen(2);fmt.Println(s)','[0 0]','Адрес заголовка позволяет изменить длину в пределах capacity.','','fmt,reflect');
q('Call не преобразует аргумент','defer func(){fmt.Println(recover()!=nil)}();f:=reflect.ValueOf(func(int64){});f.Call([]reflect.Value{reflect.ValueOf(int32(1))})','true','Отражённый вызов проверяет присваиваемость типов так же, как обычный вызов.','','fmt,reflect');
section('Строки, байты, руны и текстовые типы');
q('Число в строку — кодовая точка','n:=65;fmt.Println(string(rune(n)),strconv.Itoa(n))','A 65','Конверсия целого в string кодирует Unicode-символ, а форматирование пишет десятичные цифры.','','fmt,strconv');
q('Невалидная Unicode-точка','r:=rune(0xD800);fmt.Printf("%q %d\\n",string(r),len(string(r)))','"�" 3','Суррогат недопустим как Unicode scalar value и заменяется U+FFFD в UTF-8.');
q('Отрицательная кодовая точка','r:=rune(-1);fmt.Println(string(r)=="\uFFFD")','true','Отрицательная кодовая точка тоже даёт символ замены.');
q('byte и rune при индексе','s:="я";fmt.Printf("%T %d %d\\n",s[0],s[0],[]rune(s)[0])','uint8 209 1103','Индекс строки возвращает байт UTF-8, а не Unicode-символ.');
q('Срез внутри UTF-8','s:="я";fmt.Println(len(s[:1]),utf8.ValidString(s[:1]))','1 false','Границы slicing задаются байтовыми индексами и не обязаны совпадать с границами rune.','','fmt,unicode/utf8');
q('Два невалидных байта','s:="\\xff\\xff";fmt.Println(len(s),len([]rune(s)),len(string([]rune(s))))','2 2 6','Каждый невалидный байт даёт отдельную rune U+FFFD, кодирующуюся тремя байтами.');
q('Rune range выдаёт байтовый индекс','for i,r:=range "aяb"{fmt.Printf("%d:%U ",i,r)};fmt.Println()','0:U+0061 1:U+044F 3:U+0062 ','Индекс range по строке — смещение в байтах, даже когда второе значение имеет тип rune.');
q('Копия при []byte в string','b:=[]byte("go");s:=string(b);b[0]=\'n\';fmt.Println(s,string(b))','go no','Обычная конверсия гарантирует независимость строки от последующих изменений исходных байтов.');
q('Копия при string в []byte','s:="go";b:=[]byte(s);b[0]=\'n\';fmt.Println(s,string(b))','go no','Полученные байты изменяемы, исходная строка остаётся прежней.');
q('Nil []byte в string','var b []byte;s:=string(b);fmt.Println(s=="",len(s))','true 0','У строк нет nil-значения; nil-срез преобразуется в пустую строку.');
q('Пустая строка в []byte','b:=[]byte("");fmt.Println(b==nil,len(b))','false 0','Конверсия строки в срез создаёт не-nil срез, в том числе для пустой строки.');
q('Определённый byte в срезе','b:=[]B{65,66};fmt.Println(string(b))','AB','Специальная строковая конверсия допускает срез с элементом, underlying type которого byte.','type B byte');
q('Определённая rune в срезе','r:=[]R{1103};fmt.Println(string(r))','я','Специальная строковая конверсия допускает определённые типы с underlying int32.','type R rune');
bad('int не rune для среза','fmt.Println(string([]int{65}))','cannot convert','Поддержка целого скаляра не означает поддержку среза произвольного целочисленного типа.');
q('Строка в срез определённых байтов','b:=[]B("go");fmt.Printf("%T %v\\n",b,b)','[]main.B [103 111]','Специальная конверсия из строки сохраняет явно заданный тип элементов.','type B byte');
q('Copy строки в байты','b:=make([]byte,3);n:=copy(b,"яx");fmt.Println(n,b)','3 [209 143 120]','Специальная форма copy переносит байты, не руны.');
q('Append строки к байтам','b:=append([]byte{65},"я"...);fmt.Println(b)','[65 209 143]','Для []byte append разрешает строковый аргумент с ..., добавляя UTF-8-байты.');
bad('Append строки к рунам','r:=append([]rune{},"я"...);fmt.Println(r)','cannot use','Строковое исключение append относится к байтам; декодирование в руны требуется явно.');
q('Rune не графема','s:="e\u0301";fmt.Println(len(s),utf8.RuneCountInString(s),s=="é")','3 2 false','Go сравнивает последовательности байтов и не выполняет Unicode-нормализацию.','','fmt,unicode/utf8');
q('Определённый string в результате +','var s S="go";fmt.Printf("%T %v\\n",s+"!",s+"!")','main.S go!','Нетипизированная строковая константа адаптируется к определённому типу другого операнда.','type S string');
section('Составные ловушки: память, generics и итераторы');
q('Sizeof не вызывает функцию','n:=0;f:=func()int{n++;return 1};_ = unsafe.Sizeof(f());fmt.Println(n)','0','Размер значения фиксирован его типом; операнд Sizeof не вычисляется.','','fmt,unsafe');
q('Размер интерфейса не размер данных','var a any=[100]int{};var b any=byte(1);fmt.Println(unsafe.Sizeof(a)==unsafe.Sizeof(b))','true','Sizeof интерфейса измеряет его представление, а не динамический объект.','','fmt,unsafe');
q('Размер среза не зависит от длины','a,b:=make([]byte,1),make([]byte,1000);fmt.Println(unsafe.Sizeof(a)==unsafe.Sizeof(b))','true','Sizeof измеряет заголовок среза, не массив элементов.','','fmt,unsafe');
q('Unsafe.Slice с nil и нулём','var p *int;s:=unsafe.Slice(p,0);fmt.Println(s==nil)','true','Нулевая длина допускает nil-указатель и возвращает nil-срез.','','fmt,unsafe');
q('Unsafe.Slice с nil и длиной','defer func(){fmt.Println(recover()!=nil)}();var p *int;_ = unsafe.Slice(p,1)','true','Для ненулевой длины nil-указатель недопустим даже в unsafe.Slice.','','fmt,unsafe');
q('Unsafe.SliceData nil-среза','var s []int;fmt.Println(unsafe.SliceData(s)==nil)','true','SliceData гарантирует nil для nil-среза; это не правило для любого пустого среза.','','fmt,unsafe');
q('Unsafe.Add внутри массива','a:=[2]uint32{1,2};p:=(*uint32)(unsafe.Add(unsafe.Pointer(&a[0]),unsafe.Sizeof(a[0])));*p=9;fmt.Println(a)','[1 9]','Смещение задано в байтах и остаётся внутри исходного массива; типизированный указатель обращается ко второму элементу.','','fmt,unsafe');
q('Unsafe.String с пустым nil','fmt.Println(unsafe.String(nil,0)=="")','true','Пустая строка может быть построена из nil-указателя при нулевой длине.','','fmt,unsafe');
q('Указатель на массив в any после смены среза','s:=[]int{1};var a any=(*[1]int)(s);s=append(s,2);s[0]=9;fmt.Println(a.(*[1]int)[0])','1','Интерфейс сохраняет указатель на старый массив, а не связь с переменной среза.');
q('Generic Comparable с interface-полем','defer func(){fmt.Println(recover()!=nil)}();v:=Box[any]{[]int{}};fmt.Println(eq(v,v))','true','Box[any] удовлетворяет comparable, однако поле содержит несравнимый динамический срез.','type Box[T any]struct{V T};func eq[T comparable](a,b T)bool{return a==b}');
q('Метод только у *T: связанное ограничение','fmt.Println(build[N,*N]())','1','Второй параметр связывает указатель *T с требуемым методом, позволяя безопасно создать ненулевой receiver.','type N int;func(n *N)Inc(){*n++};func build[T any,P interface{*T;Inc()}]()T{p:=P(new(T));p.Inc();return *p}');
q('Нулевой generic receiver остаётся nil','defer func(){fmt.Println(recover()!=nil)}();fmt.Println(build[*N]())','true','Ограничение методом не обещает пригодность нулевого значения T к вызову этого метода.','type N int;func(n *N)Inc(){*n++};func build[T interface{Inc()}]()T{var t T;t.Inc();return t}');
q('Constraint со своим типом','fmt.Println(equal(N(1),N(1)))','true','Параметр ограничения связывает тип аргумента метода с тем же T.','type N int;func(n N)Equal(m N)bool{return n==m};func equal[T interface{Equal(T)bool}](a,b T)bool{return a.Equal(b)}');
bad('any в параметре метода не свой тип','fmt.Println(equal(N(1),N(1)))','does not satisfy','Equal(any) не реализует требуемую сигнатуру Equal(N), несмотря на возможность отдельного вызова.','type N int;func(n N)Equal(m any)bool{return true};func equal[T interface{Equal(T)bool}](a,b T)bool{return a.Equal(b)}');
q('Тип переменной range по целому','var n N=3;for i:=range n{fmt.Printf("%T:%v ",i,i)};fmt.Println()','main.N:0 main.N:1 main.N:2 ','При range по типизированному целому новая переменная имеет тот же тип.','type N int');
bad('Range по union с разной базой','f(int32(2))','cannot range over','В Go 1.23 типы int и int32 не образуют единую основу для range по параметру типа.','func f[T ~int|~int32](n T){for range n{}}','');
q('Итератор сохраняет тип элемента','s:=func(yield func(N)bool){yield(7)};for v:=range s{fmt.Printf("%T %v\\n",v,v)}','main.N 7','Тип параметра yield определяет тип переменной range, сохраняя определённый N.','type N int');
q('break возвращает false источнику','s:=func(yield func(int)bool){fmt.Println(yield(1))};for v:=range s{fmt.Println(v);break}','1\nfalse','Выход потребителя через break сигнализирует источнику, что дальнейшие значения не нужны.');
q('Итератор нарушает типизированный протокол','defer func(){fmt.Println(recover()!=nil)}();s:=func(yield func(int)bool){yield(1);yield(2)};for range s{break}','true','Правильная сигнатура не доказывает соблюдение протокола: повторный yield после false вызывает panic.');
bad('yield с числовым результатом','s:=func(yield func(int)int){yield(1)};for range s{}','cannot range over','Протокол range требует булев результат yield; числовой код продолжения не подходит.','','');
