// Code generated by go generate; DO NOT EDIT.
package algorithms

func FindUsersGenerated(src []User, pred func(User) bool) int {
	for i, item := range src {
		if pred(item) {
			return i
		}
	}
	return -1
}
func AllUsersGenerated(src []User, pred func(User) bool) bool {
	for _, item := range src {
		if !pred(item) {
			return false
		}
	}
	return true
}
func MapUsersGenerated(src []User, fn func(User) string) []string {
	if src == nil {
		return nil
	}
	out := make([]string, len(src))
	for i, item := range src {
		out[i] = fn(item)
	}
	return out
}

func FindIntsGenerated(src []int, pred func(int) bool) int {
	for i, item := range src {
		if pred(item) {
			return i
		}
	}
	return -1
}
func AllIntsGenerated(src []int, pred func(int) bool) bool {
	for _, item := range src {
		if !pred(item) {
			return false
		}
	}
	return true
}
func MapIntsGenerated(src []int, fn func(int) string) []string {
	if src == nil {
		return nil
	}
	out := make([]string, len(src))
	for i, item := range src {
		out[i] = fn(item)
	}
	return out
}
