package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"text/template"
)

const source = `// Code generated by go generate; DO NOT EDIT.
package algorithms
{{range .}}
func Find{{.Name}}Generated(src []{{.Element}}, pred func({{.Element}}) bool) int {
 for i, item := range src { if pred(item) { return i } }; return -1
}
func All{{.Name}}Generated(src []{{.Element}}, pred func({{.Element}}) bool) bool {
 for _, item := range src { if !pred(item) { return false } }; return true
}
func Map{{.Name}}Generated(src []{{.Element}}, fn func({{.Element}}) {{.Result}}) []{{.Result}} {
 if src == nil { return nil }; out := make([]{{.Result}}, len(src))
 for i, item := range src { out[i] = fn(item) }; return out
}
{{end}}`

func main() {
	specs := []struct{ Name, Element, Result string }{
		{"Users", "User", "string"},
		{"Ints", "int", "string"},
	}
	tmpl, err := template.New("algorithms").Parse(source)
	if err != nil {
		log.Fatal(err)
	}
	var buffer bytes.Buffer
	if err := tmpl.Execute(&buffer, specs); err != nil {
		log.Fatal(err)
	}
	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("generated_algorithms.go", formatted, 0644); err != nil {
		log.Fatal(err)
	}
}
